version: '3.8'

services:
  dev-database:
    image: postgres:16.1s
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "12345678"
      POSTGRES_DB: "MicroserviceStudy"
    networks:
      - nestjs-network

  consul:
    image: hashicorp/consul:latest
    ports:
      - "8500:8500"
      - "8502:8502"
    command: agent -dev -client=0.0.0.0
    networks:
      - nestjs-network

networks:
  nestjs-network:
